### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Anthony1234567** [Anthony1234567/CECS543_Project-1#7]
Require documentation:

- Use cases
- User scenario (done) 
- Work breakdown structure (done)
- Product Backlog (done)
- Progress Board
- Standup Status (twice weekly)
- Readme

**Comment by sotheanithsok** [comment]
**Use Cases**
**Title**: Create Repository
**Tag-line**: Create a repository for the given project source tree (including all its files and their folder
paths) within the project.
**Summary**: The user needs to keep track of various snapshots of their project. Each snapshot includes
the current state of each file in their project tree at a specific moment during project development. In
order to keep track of each snapshot, we create a repository (repo) in the given target folder and copy
a snapshop of the source tree in the given source folder. The entire source project tree folder
(including its root folder) is replicated within (and immediately under) the target repository root
folder. Additionally, on creation, a manifest (i.e., a snapshot summary) for this command is created
listing the command particulars (i.e., the command line used), the date and time of the command, and
for each project source file a line describing that source file (AKA that artifact) in the project along
with its project folder's relative path. Because we expect, eventually, to store more than one artifact of
each project file, we put the first artifact of a file under a new (non-project) leaf folder, where the leaf
folder is given the file's name and the artifact gets an artifact ID (a code name). Note the contents of
the artifact file is the same as its corresponding project source file snapshot. The leaf folder appears in
the repository in same relative position as its corresponding file appears in the project source folder.
The artifact ID format is described below

**Comment by sotheanithsok** [comment]
**User Scenario**
Write up a User Scenario which describes what the user wants the VCS to do, as an
assistant to the user, and why the user wants that. Focus on the kinds of requests the user might make
to the VCS. Also, indicate which features your team would like to implement (if time permits).

**Comment by sotheanithsok** [comment]
**Work breakdown structure**
What is your current estimated hierarchy of tasks (WBS)?
Indicate the task to sub-task relationships, if any. Note that these can be changed during project
development. When modified, include it in a zip with the next Standup Status report. Give each task a
number (and don't reuse numbers if you add/delete tasks).

**Comment by sotheanithsok** [comment]
**Progress Board**
Which WBS tasks have been A) Begun, by whom? B) Completed (and can be
demonstrated) by whom, when? C) Verified (QA'd) by whom, when? Include the current Progress
Board file at the end of each Standup Status report

**Comment by sotheanithsok** [comment]
**Standup Status (twice weekly)**
The Standup Status Report is due Sunday by 11pm and on the day
before the last class session of the week at 11pm. One report per team. It should contain, for each
team member, their Standup answers to the 3 standard Standup questions: Q1. What task(s) have you
completed since last status? Q2. What task(s) do you plan to complete by next status? Q3. What
obstacles are blocking your progress (on which task(s))? Consider sub-dividing a WBS task into "HalfDay" sub-tasks so as to be able to have a task completion (or more) for each status. Note that if a team
member takes on a WBS task and sub-tasks it, then the sub-tasks should be added to the WBS and
shown on the Progress Board. Also, note that keeping track of tasks, new/old sub-tasks, and
completions takes effort, but can be streamlined. Don't forget that merging your completed task code
into the team's mainline code requires integration testing. Tasks that have gone through QA should be
demonstratable in class.

**Comment by sotheanithsok** [comment]
**Readme File**
You should provide a README.txt text file. Be clear in your instruction on how to build and use
the project by providing instructions a novice programmer would understand. If there are any external
dependencies for building, the README must also list them and how to find and incorporate them.
Usage should include an example invocation. A README would cover the following:
• Class number
• Project name
• Team name and members
• Intro (use the tag line, above)
• Contents: Files in the .zip submission
• External Requirements (Node, etc.)
• Setup and Installation (if special)
• Sample invocation & results to see
• Features (both included and missing)
• Bugs (if any)

**Comment by sotheanithsok** [comment]
**Product Backlog**
What are the tasks/features that are left to build?
